name = "call-tracking-forwarder"
compatibility_date = "2024-09-23"
pages_build_output_dir = "public"

[[d1_databases]]
binding = "DB"
database_name = "call-tracking-db"
database_id = "393adb3a-c723-4af3-b205-6b5cf677030d"
